force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <formula>TEXT(Contact__r.Nationality__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TEstAppType.cls
@isTest
public class TEstAppType {

    @isTest
    static void TestContact() {
        // Create test Contacts
        List<Contact> contact = new List<Contact>{
            new Contact(LastName='yc', Nationality__c='Malaysian'),
            new Contact(LastName='Users', Nationality__c='Singaporean')
        };
        insert contact;
        
    }
    
        @IsTest
    static void testDomesticApplication() {
        // Query the Domestic contact
        Contact domesticCon = [SELECT Id ,  Nationality__c FROM Contact];

       List<Application__c> app = new List<Application__c>{
            new Application__c(Name='Domestic'  ),
            new Application__c(Name='International')
        };
        insert app;
       
    }
    
    @IsTest
    static void testSelectDom(){
     List<Program_Requirement__mdt> InterProgReqs = [
        SELECT MasterLabel, Requirement_Type__c FROM Program_Requirement__mdt
        WHERE Requirement_Type__c = 'International'
    ];
    }
    

}